name: Docker Image CI

on: [push, pull_request]

jobs:

  build_mips:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: MIPS Little Endian x32
      run: |
          docker build . --build-arg ARCH=mipsel-lts -t mipsel-lts-linux-gnu --file Dockerfile
          docker run mipsel-lts-linux-gnu > mipsel-lts-linux-gnu
          chmod +x mipsel-lts-linux-gnu
          sudo ./mipsel-lts-linux-gnu bash
          chmod +x configure CL.sh
          ls -lt
          ./CL.sh mipsel-unknown-linux-gnu
          

    #- name: MIPS Big Endian x32
    #  if: success()
    #  run: |
    #      docker build . --build-arg ARCH=mips --build-arg HOST=mipsel-unknown-linux-gnu -t mips-linux-gnu --file Dockerfile
    #      docker run mipsel-linux-gnu > mipsel-lts-linux-gnu
    #      chmod +x mipsel-linux-gnu
    #      ./mipsel-linux-gnu bash
