name: Cross-Release

on: [push]

jobs:

  build_mips:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: MIPS Little Endian x32
      run: |
          docker build . --build-arg ARCH=mipsel-lts --build-arg HOST=mipsel-unknown-linux-gnu --no-cache -t mipsel-lts-linux-gnu --file Dockerfile
          docker run --name release mipsel-lts-linux-gnu 
          #docker ps -a
          docker cp release:/work/release .
    - name: Upload binary artifacts
      uses: actions/upload-artifact@v3
      with:
          name: mipsel-unknown-linux-gnu-bin
          path: ./release/
          if-no-files-found: error
    - name: Archive binary
      if: "startsWith(github.ref, 'refs/tags/')"
      run: |
        cd ./release
        tar czvf mipsel-unknown-linux-gnu-bin.tar.gz -C ./ .
        cd -
    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v1
      if: "startsWith(github.ref, 'refs/tags/')"
      with:
        files: ./release/mipsel-unknown-linux-gnu-bin.tar.gz
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        generate_release_notes: true

    #- name: MIPS Big Endian x32
    #  if: success()
    #  run: |
    #      docker build . --build-arg ARCH=mips --build-arg HOST=mipsel-unknown-linux-gnu -t mips-linux-gnu --file Dockerfile
    #      docker run mipsel-linux-gnu > mipsel-lts-linux-gnu
    #      chmod +x mipsel-linux-gnu
    #      ./mipsel-linux-gnu bash
