name: Release

on: [push]

jobs:

  build_mips:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: MIPS Little Endian x32
      run: |
          mkdir /opt/release
          docker build . --build-arg ARCH=mipsel-lts --build-arg HOST=mipsel-unknown-linux-gnu --no-cache -t mipsel-lts-linux-gnu --file Dockerfile
          docker run --name release mipsel-lts-linux-gnu
          docker cp release:/user/local/musl/sbin/*davfs /opt/release/
    - name: Upload binary artifacts
      uses: actions/upload-artifact@v3
      with:
          name: mipsel-unknown-linux-gnu-bin
          path: /opt/release/*davfs
          if-no-files-found: error

    #- name: MIPS Big Endian x32
    #  if: success()
    #  run: |
    #      docker build . --build-arg ARCH=mips --build-arg HOST=mipsel-unknown-linux-gnu -t mips-linux-gnu --file Dockerfile
    #      docker run mipsel-linux-gnu > mipsel-lts-linux-gnu
    #      chmod +x mipsel-linux-gnu
    #      ./mipsel-linux-gnu bash
